ofdocbuild:
    build: .
    #image: openframeworks/docs
    environment:
        OF_ROOT: /openframeworks
        OF_DOCUMENTATION_ROOT: /markdown
        OF_DOCUMENTATION_SITE_OUTPUT: /site
        OF_DOCUMENTATION_JSON_DIR: /tmp/json
    volumes:
        - .:/src:ro
        - $OF_PATH:/openframeworks:ro
        - $OF_MARKDOWN_DOCUMENTATION_PATH:/markdown:ro
        - ./_dsite/:/site
    #command: /bin/bash -c "python /src/src/main.py"

web:
    image: nginx
    volumes:
        - ./_dsite:/usr/share/nginx/html:ro
    ports:
        - "80:80"
    restart: always

jenkins:
    image: jenkins
    volumes:
        - ./jenkins_data:/var/jenkins_home
    ports:
        - "8080:8080"
    restart: always
