ofdocbuild:
    build: ./docker_docsbuilder
    #image: openframeworks/docs
    environment:
        #OF_ROOT: /openframeworks
        #OF_DOCUMENTATION_ROOT: /markdown
        OF_DOCUMENTATION_SITE_OUTPUT: /site
        OF_DOCUMENTATION_JSON_DIR: /tmp/json
    volumes:
        - ./src:/src:ro
        - ./jenkins_data/workspace:/jenkins_workspace
        #- $OF_PATH:/openframeworks:ro
        #- $OF_MARKDOWN_DOCUMENTATION_PATH:/markdown:ro
        - ./_docker_site/:/site
    restart: always

web:
    image: nginx
    volumes:
        - ./_docker_site:/usr/share/nginx/html:ro
    ports:
        - "80:80"
    restart: always

jenkins:
    build: ./docker_jenkins
    volumes:
        - ./jenkins_data:/var/jenkins_home
    ports:
        - "8080:8080"
    restart: always
    links:
        - "ofdocbuild"
