ofdocbuild:
    build: .
    #image: openframeworks/docs
    volumes:
        - .:/ofDocumentationGenerator
        - $OF_PATH:/openframeworks
        - $OF_MARKDOWN_DOCUMENTATION_PATH:/markdown
    command: /bin/bash -c "cd /ofDocumentationGenerator; python src/main.py /openframeworks/; python src/parse_markdown.py /markdown; python src/generate_site.py /markdown;"
    #command: /bin/bash -c "python /ofDocumentationGenerator/src/generate_site.py;"
web:
    image: nginx
    volumes:
        - ./_site:/usr/share/nginx/html:ro
    ports:
        - "80:80"
    restart: always
