ofdocbuild:
    build: .
    #image: openframeworks/docs
    volumes:
        - .:/ofDocumentationGenerator
        - $OF_PATH:/openframeworks
    command: /bin/bash -c "python /ofDocumentationGenerator/src/documentation_update.py /openframeworks/; python /ofDocumentationGenerator/src/generate_site.py;"
    #command: /bin/bash -c "python /ofDocumentationGenerator/src/generate_site.py;"
web:
    image: nginx
    volumes:
        - ./_site:/usr/share/nginx/html:ro
    ports:
        - "80:80"
