ofdocbuild:
    build: ./docker_docsbuilder
    container_name: ofdocbuilder
    environment:
        OF_ROOT: /openframeworks
        OF_DOCUMENTATION_ROOT: /markdown
        OF_DOCUMENTATION_SITE_OUTPUT: /site
        OF_DOCUMENTATION_JSON_DIR: /site/json
    volumes:
        # The python source code
        - ./src:/src:ro
        # openframeworks directory
        - $OF_PATH:/openframeworks:ro
        # Markdown directory
        - $OF_MARKDOWN_DOCUMENTATION_PATH:/markdown:ro
        # Output directory
        - ./_output/:/site

web:
    image: nginx
    volumes:
        - ./_output:/usr/share/nginx/html:ro
        #- ./docker_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./docker_nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
        - "8080:80"
