ofdocbuild:
    build: ./docker_docsbuilder
    volumes:
        # The python source code
        - ./src:/src:ro

        # Jenkins workspace will contain markdown and openframeworks
        - ./jenkins_data/workspace:/jenkins_workspace

        # Output directory
        - ./_docker_site/:/site
    restart: always

web:
    image: nginx
    volumes:
        - ./_docker_site:/usr/share/nginx/html:ro
    ports:
        - "80:80"
    restart: always

jenkins:
    build: ./docker_jenkins
    volumes:
        - ./jenkins_data:/var/jenkins_home
    ports:
        - "8080:8080"
    restart: always
    links:
        - "ofdocbuild"
